RegLogin/Login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^login/action', views.login_action, name='login_action'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register/action', views.reg_action, name='reg_action'),


]

RegLogin/RegLogin/urls.py
from django.conf.urls import url , include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/', include('Login.urls',  namespace='Index')),
]

RegLogin/Login/models.py
from __future__ import unicode_literals

from django.db import models

class Login(models.Model):
    username = models.CharField(max_length=20, null=False)
    password = models.CharField(max_length=32, null=False)
    is_ban = models.BooleanField(null=False, default=False)
    role = models.CharField(max_length=1, null=False, default=1)
    email = models.CharField(max_length=50, null=True)
    phone = models.CharField(max_length=11, null=True)
    register_time = models.DateTimeField(null=False, auto_now=True)
    last_login_time = models.DateTimeField(null=False, auto_now=True)

RegLogin/Login/views.py
#coding=utf-8
from django.shortcuts import render
from django.contrib import auth
from django.contrib.auth.models import User

def index(request):
    return render(request, 'Login/index.html')

def login(request):
    return render(request, 'Login/login.html')

def login_action(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = auth.authenticate(username=username, password=password)
    if user is not None and user.is_active:
        auth.login(request, user)
        request.session['user'] = username
        return render(request, 'Login/index.html', {'message': "login sucess"})
    else:
        return render(request, 'Login/login.html', {'message': {'text':"用户名或密码错误！",'color':'red'}})

def register(request):
    return render(request, 'Login/register.html')

def reg_action(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    email = request.POST.get('email')
    User.objects.create_user(username=username, password=password, email=email)
    return render(request, 'Login/login.html', {'message': {'text':"注册成功！",'color':'yellow'}})

RegLogin/Login/templates/Login/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
<h1>登录成功</h1>
</body>
</html>

RegLogin/Login/templates/Login/login.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>登录</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link rel="stylesheet" href="{% static "css/style.css" %}" />

<body>

<div class="login-container">
	<h1>用户登录</h1>
	<div class="connect">
        <h2 style="color: {{ message.color }} ;text-align: center;font-size: 15px;" ><b>{{ message.text }}</b></h2>
		<p>www.tayfl1314.cn</p>
	</div>

	<form action="{% url 'Index:login_action' %}" method="post">
        {% csrf_token %}
		<div>
			<input type="text" name="username" class="username" placeholder="用户名"/>
		</div>
		<div>
			<input type="password" name="password" class="password" placeholder="密码" oncontextmenu="return false" onpaste="return false" />
		</div>
		<button id="submit" type="submit">登 录</button>
	</form>

	<a href="{% url 'Index:register' %}">
		<button type="button" class="register-tis">还有没有账号？</button>
	</a>

</div>

<script src="{% static "js/jquery.min.js" %}"></script>
<script src="{% static "js/common.js" %}"></script>
<!--背景图片自动更换-->
<script src="{% static "js/supersized.3.2.7.min.js" %}"></script>
<script src="{% static "js/supersized-init.js" %}"></script>
<!--表单验证-->
<script src="{% static "js/jquery.validate.min.js" %}"></script>
<script src="http://www.mycodes.net/js/tongji.js"></script>
<script src="http://www.mycodes.net/js/youxia.js" type="text/javascript"></script>

</body>
</html>

RegLogin/Login/templates/Login/register.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>注册</title>
<link rel="stylesheet" href="{% static "css/style.css" %}" />
<body>

<div class="register-container">
	<h1>用户注册</h1>
	
	<div class="connect">
		<p>Link the world. Share to world.</p>
	</div>
	
	<form method="post" action="{% url 'Index:reg_action' %}">
        {% csrf_token %}
		<div>
			<input type="text" name="username" class="username" placeholder="您的用户名" autocomplete="off"/>
		</div>
		<div>
			<input type="password" name="password" class="password" placeholder="输入密码" oncontextmenu="return false" onpaste="return false" />
		</div>
		<div>
			<input type="password" name="confirm_password" class="confirm_password" placeholder="再次输入密码" oncontextmenu="return false" onpaste="return false" />
		</div>
{#		<div>#}
{#			<input type="text" name="phone_number" class="phone_number" placeholder="输入手机号码" autocomplete="off" id="number"/>#}
{#		</div>#}
		<div>
			<input type="email" name="email" class="email" placeholder="输入邮箱地址" oncontextmenu="return false" onpaste="return false" />
		</div>

		<button id="submit" type="submit">注 册</button>
	</form>
	<a href="{% url 'Index:login' %}">
		<button type="button" class="register-tis">已经有账号？</button>
	</a>

</div>


<script src="{% static "js/jquery.min.js" %}"></script>
<script src="{% static "js/common.js" %}"></script>
<!--背景图片自动更换-->
<script src="{% static "js/supersized.3.2.7.min.js" %}"></script>
<script src="{% static "js/supersized-init.js" %}"></script>
<!--表单验证-->
<script src="{% static "js/jquery.validate.min.js" %}"></script>

</body>
</html>