myblog/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.index),
    url(r'^article/(?P<article_id>[0-9]+)$', views.article_page, name='article'),
    url(r'^edit/(?P<article_id>[0-9]+)$', views.edit_page, name='edit'),
    url(r'^edit/action$', views.edit_action, name='edit_action'),
]

myblog/myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

myblog/blog/models.py
from __future__ import unicode_literals

from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=32, default='Title')
    content = models.TextField(null=True)
    pub_time = models.DateTimeField(null=True)

    def __unicode__(self):
        return self.title

myblog/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models

def index(request):
        articles = models.Article.objects.all()
        return render(request, 'blog/index.html', {'articles':articles})

def article_page(request, article_id):
        article = models.Article.objects.get(pk=article_id)
        return render(request, 'blog/article.html', {'article':article})

def edit_page(request, article_id):
        if article_id == '0':
            return render(request, 'blog/edit.html')
        article = models.Article.objects.get(pk=article_id)
        return render(request, 'blog/edit.html', {'article':article})

def edit_action(request):
        title = request.POST.get('title', 'TITLE')
        content = request.POST.get('content', 'CONTENT')
        article_id = request.POST.get('article_id', 0)
        if article_id == '0':
            models.Article.objects.create(title=title, content=content)
            articles = models.Article.objects.all()
            return render(request, 'blog/index.html', {'articles':articles})
        article = models.Article.objects.get(pk=article_id)
        article.title = title
        article.content = content
        article.save()
        return render(request, 'blog/article.html', {'article':article})

myblog/blog/templates/blog/article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ article.title }}</h1>
<br>
<h3>{{ article.content }}</h3>
<br><br>
<a href="{% url 'blog:edit' article.id %}">修改文章</a>
</body>
</html>

myblog/blog/templates/blog/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Page</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="article_id" value="{{ article.id | default:'0' }}"/>
    <label for="">标题
        <input type="text" name="title" value="{{ article.title }}">
    </label>
    <br><br>
    <label for="">正文
{#        <textarea name="content" id="" cols="22" rows="10"></textarea>#}
        <input type="text" name="content" value="{{ article.content }}">
    </label>
    <br><br>
    <input type="submit">
</form>
</body>
</html>

myblog/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1><a href="{% url 'blog:edit' 0 %}">新文章</a></h1>
<br/>
{% for article in articles %}
    <a href="{% url 'blog:article' article.id %}">{{ article.title }}</a>
    <br/>
{% endfor %}
</body>
</html>